package edu.usfca.cs;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * SongTest is the class to test methods in the Song class
 * Generated by jUnit
 * <p>
 * @author      Gizem Hazal Senturk
 * @since       1.0
 */


class SongTest {

    String artist1, artist2, artist3, artist4, artist5, artist6, artist7, artist8, artist10;
    Song s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11;
    Boolean T=true, F=false;

    @BeforeEach
    void setUp(){

        s1 = new Song("Song 1", "Album 1", "artist1");
        s2 = new Song("Song 2", 339, "Album 2", artist2, F , "jazz");
        s3 = new Song("Song 3",40, "Album 3", artist3, T , "pop");
        s4 = new Song("Song 4", 339,"Album 4", artist4, T , "rock");
        s5 = new Song("Song 5",40,"Album 5", artist5, T ,"jazz");
        s6 = new Song("Song 6", 339, "Album 6", artist6, T ,"jazz");
        s7 = new Song("Song 7",40, "Album 7", artist7, F, "r&b");
        s8 = new Song("Song 8", 339, "Album 8", artist8, F ,"jazz");

        // Songs to test duplicates and addition
        s9 = new Song("Song 1", 40, "Album 1", "Artist 1", T);
        s10 = new Song("Song 10", 40, "Album 1", artist10 , T);
        s11 = new Song("Song 1", "Album 1", "artist1");

    }

    @Test
    void testEquals() {
        assertTrue(s1.equals(s11));
    }

    @Test
    void testToString() {
        System.out.println(s1.toString());
    }

    @Test
    void toXML() {
        System.out.println(s1.toXML());
    }

    @Test
    void toJSON() {
        System.out.println(s1.toJSON());
    }

}